framework:
  notifier:
    chatter_transports:
    texter_transports:
    channel_policy:
      # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
      urgent: ["mail"]
      high: ["mail"]
      medium: ["mail"]
      low: ["mail"]
    admin_recipients:
      - { email: admin@example.com }
